### ISSUE TITLE
[bug] QtDriver.detect_qt is not finding the driver

### ISSUE THREAD

**Issue by rodrigomologni** [hmeine/qimage2ndarray#28]
Hi developers!

The package is not working without PyQt5:

```sh
Traceback (most recent call last):
  File "D:\Users\Rodrigo\Desktop\temp.py", line 1, in <module>
    import qimage2ndarray
  File "d:\users\rodrigo\github\qimage2ndarray\qimage2ndarray\__init__.py", line 4, in <module>
    from .dynqt import QtGui as _qt
  File "d:\users\rodrigo\github\qimage2ndarray\qimage2ndarray\dynqt.py", line 4, in <module>
    QtGui = qt.QtGui
  File "d:\users\rodrigo\github\qimage2ndarray\qimage2ndarray\qt_driver.py", line 131, in __getattr__
    return self.importMod(name)
  File "d:\users\rodrigo\github\qimage2ndarray\qimage2ndarray\qt_driver.py", line 126, in importMod
    qt = __import__('%s.%s' % (self._drv, mod))
ModuleNotFoundError: No module named 'PyQt5'
[Finished in 369ms]
```

The error occurs because the method `QtDriver.detect_qt` is not finding the driver. It always returns `None`.

**Comment by rodrigomologni** [comment]
`detect_qt` uses [`sys.modules`](https://docs.python.org/3/library/sys.html#sys.modules). This property maps only modules which have already been loaded. An alternative is:

```python
def detect_qt():
    for qt in ["PyQt6", "PySide6", "PyQt5", "PySide2"]:
        try:
            exec(f"import {qt}")
        except ModuleNotFoundError:
            pass
        else:
            return qt
```
