### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by jakirkham** [hmeine/qimage2ndarray#9]
When running the test suite, I am seeing some errors. One is no module `compat`. The other seems to be due to missing files.

```
$ python setup.py nosetests
running nosetests
running egg_info
writing requirements to qimage2ndarray.egg-info/requires.txt
writing qimage2ndarray.egg-info/PKG-INFO
writing top-level names to qimage2ndarray.egg-info/top_level.txt
writing dependency_links to qimage2ndarray.egg-info/dependency_links.txt
reading manifest file 'qimage2ndarray.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'qimage2ndarray.egg-info/SOURCES.txt'
EFFFEE
======================================================================
ERROR: Failure: ImportError (No module named compat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/zopt/conda2/conda-bld/work/qimage2ndarray-1.5.1/test/test_array2qimage.py", line 5, in <module>
    from compat import numBytes, numColors
ImportError: No module named compat

======================================================================
ERROR: Failure: ImportError (No module named compat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/zopt/conda2/conda-bld/work/qimage2ndarray-1.5.1/test/test_qimage_views.py", line 5, in <module>
    from compat import setNumColors, numBytes
ImportError: No module named compat

======================================================================
ERROR: Failure: ImportError (No module named compat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/zopt/conda2/conda-bld/work/qimage2ndarray-1.5.1/test/test_qimageview.py", line 5, in <module>
    from compat import setNumColors, numBytes
ImportError: No module named compat

======================================================================
FAIL: Failure: AssertionError ()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/zopt/conda2/conda-bld/work/qimage2ndarray-1.5.1/test/test_implicit_imread.py", line 3, in <module>
    from test_imread import all_test_images, _locate_test_image
  File "/zopt/conda2/conda-bld/work/qimage2ndarray-1.5.1/test/test_imread.py", line 96, in <module>
    'test_colored_shadow.png'])
  File "/zopt/conda2/conda-bld/work/qimage2ndarray-1.5.1/test/test_imread.py", line 9, in _locate_test_image
    assert os.path.exists(result)
AssertionError

======================================================================
FAIL: Failure: AssertionError ()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/zopt/conda2/conda-bld/work/qimage2ndarray-1.5.1/test/test_imread.py", line 96, in <module>
    'test_colored_shadow.png'])
  File "/zopt/conda2/conda-bld/work/qimage2ndarray-1.5.1/test/test_imread.py", line 9, in _locate_test_image
    assert os.path.exists(result)
AssertionError

======================================================================
FAIL: Failure: AssertionError ()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/zopt/conda2/envs/_build/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/zopt/conda2/conda-bld/work/qimage2ndarray-1.5.1/test/test_imsave.py", line 4, in <module>
    from test_imread import all_test_images, _locate_test_image
  File "/zopt/conda2/conda-bld/work/qimage2ndarray-1.5.1/test/test_imread.py", line 96, in <module>
    'test_colored_shadow.png'])
  File "/zopt/conda2/conda-bld/work/qimage2ndarray-1.5.1/test/test_imread.py", line 9, in _locate_test_image
    assert os.path.exists(result)
AssertionError

----------------------------------------------------------------------
Ran 6 tests in 0.272s

FAILED (errors=3, failures=3)
```

**Comment by hmeine** [comment]
Thank you very much for the report.  I never ran nose through setup.py, that's why I never got these errors.

Here's what I do:

    cd test && nosetests

I would be interested in making the setup.py way work as well.  (Ideally, so that both would work.)  If anybody wants to help out with that, that would be welcome.

**Comment by jakirkham** [comment]
Yeah, I think I figured that out afterwards.

I was trying to get it to play nice in a conda build, but was having some issues getting the tests to run correctly. Will have to play with it some more.

Sure, I can give that a shot at some point.

**Comment by hmeine** [comment]
I also tried `python setup.py nosetests` in the meantime, and it just worked?!  I tried with Python 2.7 and PyQt4, and with Python 3.4 and PyQt5.  What versions are you using?
Please just re-open if the problem persists.  I don't want to ignore this issue, but I was not sure from your last comment and me trying if it is still an issue with qimage2ndarray.
